version: '3.9'

services:
  php-env:
    depends_on:
      - mysql_db
    build: .
    volumes:
      - ./src:/var/www/html/
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - ${SITE_PORT}:80

  mysql_db:
    image: mysql:latest
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  phpmyadmin:
    depends_on:
      - mysql_db
    image: phpmyadmin:latest
    container_name: ${PMA_CONTRAINER_NAME}
    restart: always
    ports:
      - ${PMA_PORT}:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  db_data: {}
